/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    `maven-publish`
    signing
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("org.jetbrains.dokka")
}

java {
    withSourcesJar()
}

val dokkaJavadocJar by tasks.registering(Jar::class) {
    dependsOn(tasks.dokkaHtml)
    from(tasks.dokkaHtml.get().outputDirectory)
    archiveClassifier.set("javadoc")
}

publishing {
    publications {
        create<MavenPublication>("release") {
            from(components["java"])

            artifact(dokkaJavadocJar)

            artifactId = "stilum" 

            pom {
                name.set("stilum")
                description.set("Short description of what your library does.")
                url.set("https://github.com/yourname/stilum")
                licenses {
                    license {
                        name.set("Apache-2.0")
                        url.set("https://www.apache.org/licenses/LICENSE-2.0")
                    }
                }
                developers {
                    developer {
                        id.set("yourname")
                        name.set("Your Name")
                        url.set("https://github.com/yourname")
                    }
                }
                scm {
                    url.set("https://github.com/yourname/stilum")
                    connection.set("scm:git:git://github.com/yourname/stilum.git")
                    developerConnection.set("scm:git:ssh://github.com:yourname/stilum.git")
                }
            }
        }
    }
}

fun cred(name: String): String? =
    providers.gradleProperty(name).orNull ?: System.getenv(name)

signing {
    val key = cred("SIGNING_KEY")
    val pass = cred("SIGNING_PASSWORD") ?: ""

    if (key.isNullOrBlank()) {
        throw GradleException("PGP signing not configured. Provide SIGNING_KEY (+ SIGNING_PASSWORD if encrypted).")
    }

    useGpgCmd()
    sign(publishing.publications)
}

kotlin {
    jvmToolchain(17)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("2.2.20")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.register<Jar>("javadocJar") {
    dependsOn(tasks.dokkaHtml)
    from(tasks.dokkaHtml.get().outputDirectory)
    archiveClassifier.set("javadoc")
}