/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.isiosis

import io.github.isiosis.stilum.Stilum
import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Stilum()
    }
}
